INSERT INTO QUEST(ID, QUESTLINE_ID, NAME, DESCRIPTION, RECURRENCE, LOCATION, DUE_DATE, REWARD, COMPLETED)
VALUES (0, NULL, 'Quest1', 'This is a quest', 'NONE', 'Home', '2023-06-21', 'A cookie!', 0);
INSERT INTO OBJECTIVE(ID, QUEST_ID, ORDERING, NAME, COMPLETED)
VALUES (0, 0, 0, 'Objective1', 0), (1, 0, 1, 'Objective2', 0);